### ISSUE TITLE
Shadow DOM support

### ISSUE THREAD

**Issue by arturbien** [scroll-into-view/compute-scroll-into-view#822]
Any plans on adding support for Shadow DOM ? It was temporarily dropped in https://github.com/stipsan/compute-scroll-into-view/pull/76

**Comment by pvojtechovsky** [comment]
I created a PR https://github.com/stipsan/compute-scroll-into-view/pull/829 for support of shadow DOM. I am not sure whether anchor problem is still there, but the implementation is little bit different than before so there is a chance that it will work now

**Comment by sPaCeMoNk3yIam** [comment]
@stipsan wdyt is needed to bring support for shadow DOMs? Better test coverage of linked PR?
