### ISSUE TITLE
Vite v3 error saying shipped as CommonJS package

### ISSUE THREAD

**Issue by janosh** [scroll-into-view/compute-scroll-into-view#833]
I'm trying to use this package over at https://github.com/janosh/svelte-multiselect with `vite` v3 and getting the following error:

> SyntaxError: Unexpected token 'export'
>  ❯ Object.compileFunction node:vm:360:18
> 
> Module `node_modules/compute-scroll-into-view/dist/index.module.js:1` seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "compute-scroll-into-view" asking them to ship the file in `.mjs` extension or add `"type": "module"` in their `package.json`.
> 
> As a temporary workaround you can try to inline the package by updating your config:
> 
> ```js
> // vitest.config.js
> export default {
>   test: {
>     deps: {
>       inline: [
>         "compute-scroll-into-view"
>       ]
>     }
>   }
> }
> ```

Any reservations about adding `"type": "module"` to `package.json`?

**Comment by stipsan** [comment]
We're now shipping `.mjs` 😄 https://github.com/scroll-into-view/compute-scroll-into-view/releases/tag/v1.0.18
